services:
  postgres:
    image: "postgres:10.5"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  average-character-cloud-backend:
    image: ghcr.io/kgtkr/average-character-cloud-backend:20250706074915180-2f6c66a-update_202606_bugfix
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - AVCC_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - AVCC_ORIGIN=http://localhost:3000
      - AVCC_MOUNT_BASE=backend/
      - AVCC_AUTH=disable
      - AVCC_SESSION=dummy
      - AVCC_SESSION_USER_ID=dummy_user
      - AVCC_LOGOUT_REDIRECT_URL=/
      - AVCC_FAKTORY_URL=tcp://faktory:7419
      - AVCC_ENQUEUE_CRON_TASK=false
      - AVCC_ENABLE_TASK_FRONT=true
      - AVCC_WORKERS=2
      - AVCC_STORAGE_BUCKET=avcc
      - AVCC_STORAGE_PATH_STYLE=true
      - AVCC_STORAGE_PUBLIC_ENDPOINT=http://localhost:9000
      - AWS_ACCESS_KEY_ID=minio-key-id
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://minio:9000
    depends_on:
      - postgres
      - redis
      - faktory
      - minio
  redis:
    image: "redis:7.0.3"
    volumes:
      - redis:/data
  faktory:
    image: contribsys/faktory:1.6.2
    volumes:
      - faktory:/var/lib/faktory/db
  minio:
    image: "quay.io/minio/minio:RELEASE.2024-03-26T22-10-45Z"
    environment:
      MINIO_ROOT_USER: minio-key-id
      MINIO_ROOT_PASSWORD: minio-secret-key
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:3000
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"
volumes:
  postgres:
  redis:
  faktory:
  minio:
